import locale
import json


class Localization:
    def __init__(self):
        self.current_lang = "en-us"
        self.languages = {
            "en-us": {
                "window_title_generator": "Playlist Generator",
				"window_title_editor": "Playlist Editor",
                "language_name": "English",
                "music_folder_label": "Music folder:",
                "browse_button": "Browse",
                "playlist_name_label": "Playlist name:",
                "seed_label": "Seed (leave empty for random):",
                "reverse_step_label": "Reverse step (0=off, 1-20):",
                "seed_format_label": "Seed format:",
                "shadow_seed_check": "Use shadow seed for advanced shuffling",
                "generate_button": "Generate playlist",
                "language_label": "Language:",
                "seed_formats": ["Digits only", "Digits and letters"],
                "default_playlist_name": "My_playlist",
                "error_open_editor": "Error opening editor: {error}",
                "error_save_settings": "Error saving settings: {error}",
                "error_no_music_folder": "Error: Specify music folder!",
                "error_no_playlist_name": "Error: Specify playlist name!",
                "error_folder_not_exist": "Error: Folder does not exist!",
                "error_reverse_step": "Error: Reverse step must be between 0 and 20!",
                "error_no_audio_files": "Error: No supported audio files in specified folder!",
                "seed_info_shadow": "Main seed: {seed} \nShadow seed: {shadow_seed} \nReverse step: {step}",
                "seed_info_step": "Main seed: {seed} | Reverse step: {step}",
                "seed_info_basic": "Main seed: {seed}",
                "playlist_created": "Playlist created! {info}",
                "error_scanning_folder": "Error scanning folder: {error}",
                "error_invalid_path": "Error: Invalid path characters",
                "track_number": "№",
                "track_name": "Track name",
                "shuffle_button": "Shuffle",
                "save_button": "Save",
                "error": "Error",
                "error_load_playlist": "Failed to load playlist: {error}",
                "error_no_tracks": "No tracks to save",
                "error_save": "Save error",
                "editor_seed_info_step": "Shuffled! Seed: {seed} | Reverse step: {step}",
                "editor_seed_info_basic": "Shuffled! Seed: {seed}",
                "seed_info_value": "Seed",
                "reverse_info_value": "Reverse step",
                "playlist_saved": "Playlist saved: {name}",
                "shuffled": "shuffled",
                "moved_up": "Moved selected tracks up",
                "moved_down": "Moved selected tracks down",
                "deleted_tracks": "Deleted {count} tracks",
                "action_undone": "Last action undone",
                "error_no_selection": "Error: No tracks selected!",
                "nothing_to_undo": "Error: Nothing to undo",
                "action_redone": "Action redone",
                "edit_paths_window_title": "Track Paths Editor",
                "new_path_label": "Full path for selected tracks:",
                "path_example_hint": "Example: /storage/0/emulated/Music/ \n               D:/Music/Ambient/Nature/",
                "apply_button": "Apply",
                "cancel_button": "Cancel",
                "error_empty_path": "Error: Path cannot be empty",
                "paths_updated": "Track paths successfully updated",
                "folder_entry_tooltip": " Right-click to clear the field ",
                "multiple_playlists_loaded": "Loaded {count} playlists",
                "tree_tooltip": " Right-click to open the path editor "
            },
            "ru-ru": {
                "window_title_generator": "Генератор плейлистов",
                "window_title_editor": "Редактор плейлистов",
                "language_name": "Русский",
                "music_folder_label": "Папка с музыкой:",
                "browse_button": "Обзор",
                "playlist_name_label": "Имя плейлиста:",
                "seed_label": "Сид (оставьте пустым для случайного):",
                "reverse_step_label": "Шаг реверса (0=выкл, 1-20):",
                "seed_format_label": "Формат сида:",
                "shadow_seed_check": "Использовать теневой сид для сложного перемешивания",
                "generate_button": "Создать плейлист",
                "language_label": "Язык:",
                "seed_formats": ["Только цифры", "Цифры и буквы"],
                "default_playlist_name": "Мой_плейлист",
                "error_open_editor": "Ошибка открытия редактора: {error}",
                "error_save_settings": "Ошибка сохранения настроек: {error}",
                "error_no_music_folder": "Ошибка: Укажите папку с музыкой!",
                "error_no_playlist_name": "Ошибка: Укажите имя плейлиста!",
                "error_folder_not_exist": "Ошибка: Папка не существует!",
                "error_reverse_step": "Ошибка: Шаг реверса должен быть числом от 0 до 20!",
                "error_no_audio_files": "Ошибка: В указанной папке нет поддерживаемых аудиофайлов!",
                "seed_info_shadow": "Основной сид: {seed} \nТеневой сид: {shadow_seed} \nШаг реверса: {step}",
                "seed_info_step": "Основной сид: {seed} | Шаг реверса: {step}",
                "seed_info_basic": "Основной сид: {seed}",
                "playlist_created": "Плейлист создан! {info}",
                "error_scanning_folder": "Ошибка сканирования папки: {error}",
                "error_invalid_path": "Ошибка: Недопустимые символы в пути",
                "track_number": "№",
                "track_name": "Название трека",
                "shuffle_button": "Перемешать",
                "save_button": "Сохранить",
                "error": "Ошибка",
                "error_load_playlist": "Не удалось загрузить плейлист: {error}",
                "error_no_tracks": "Нет треков для сохранения",
                "error_save": "Ошибка сохранения",
                "editor_seed_info_step": "Перемешано! Сид: {seed} | Шаг реверса: {step}",
                "editor_seed_info_basic": "Перемешано! Сид: {seed}",
                "seed_info_value": "Сид",
                "reverse_info_value": "Шаг реверса",
                "playlist_saved": "Плейлист сохранен: {name}",
                "shuffled": "перемешанный",
                "moved_up": "Выбранные треки перемещены вверх",
                "moved_down": "Выбранные треки перемещены вниз",
                "deleted_tracks": "Удалено {count} треков",
                "action_undone": "Последнее действие отменено",
                "error_no_selection": "Ошибка: Не выбрано ни одного трека!",
                "nothing_to_undo": "Ошибка: Нечего отменять",
                "action_redone": "Действие повторено",
                "edit_paths_window_title": "Редактор путей треков",
                "new_path_label": "Полный путь для выбранных треков:",
                "path_example_hint": "Например: /storage/0/emulated/Music/ \n                  D:/Music/Ambient/Nature/",
                "apply_button": "Применить",
                "cancel_button": "Отмена",
                "error_empty_path": "Ошибка: Путь не может быть пустым",
                "paths_updated": "Пути треков успешно обновлены",
                "folder_entry_tooltip": " Нажмите правой кнопкой мыши, чтобы очистить поле ",
                "multiple_playlists_loaded": "Загружено {count} плейлистов",
                "tree_tooltip": " Нажмите правой кнопкой мыши, чтобы открыть редактор путей "
            },
            "es-es": {
                "window_title_generator": "Generador de listas de reproducción",
                "window_title_editor": "Editor de listas de reproducción",
                "language_name": "Español",
                "music_folder_label": "Carpeta de música:",
                "browse_button": "Examinar",
                "playlist_name_label": "Nombre de la lista:",
                "seed_label": "Semilla (dejar vacío para aleatorio):",
                "reverse_step_label": "Paso inverso (0=desactivado, 1-20):",
                "seed_format_label": "Formato de semilla:",
                "shadow_seed_check": "Usar semilla oculta para mezcla avanzada",
                "generate_button": "Crear lista",
                "language_label": "Idioma:",
                "seed_formats": ["Solo dígitos", "Dígitos y letras"],
                "default_playlist_name": "Mi_lista",
                "error_open_editor": "Error al abrir el editor: {error}",
                "error_save_settings": "Error al guardar configuraciones: {error}",
                "error_no_music_folder": "¡Error: Especifique la carpeta de música!",
                "error_no_playlist_name": "¡Error: Especifique el nombre de la lista!",
                "error_folder_not_exist": "¡Error: La carpeta no existe!",
                "error_reverse_step": "¡Error: El paso inverso debe ser entre 0 y 20!",
                "error_no_audio_files": "¡Error: No hay archivos de audio compatibles en la carpeta especificada!",
                "seed_info_shadow": "Semilla principal: {seed} \nSemilla oculta: {shadow_seed} \nPaso inverso: {step}",
                "seed_info_step": "Semilla principal: {seed} | Paso inverso: {step}",
                "seed_info_basic": "Semilla principal: {seed}",
                "playlist_created": "¡Lista creada! {info}",
                "error_scanning_folder": "Error al escanear carpeta: {error}",
                "error_invalid_path": "Error: Caracteres no válidos en la ruta",
                "track_number": "№",
                "track_name": "Nombre de la pista",
                "shuffle_button": "Mezclar",
                "save_button": "Guardar",
                "error": "Error",
                "error_load_playlist": "No se pudo cargar la lista: {error}",
                "error_no_tracks": "No hay pistas para guardar",
                "error_save": "Error al guardar",
                "editor_seed_info_step": "¡Mezclado! Semilla: {seed} | Paso inverso: {step}",
                "editor_seed_info_basic": "¡Mezclado! Semilla: {seed}",
                "seed_info_value": "Semilla",
                "reverse_info_value": "Paso inverso",
                "playlist_saved": "Lista guardada: {name}",
                "shuffled": "mezclado",
                "moved_up": "Pistas seleccionadas movidas arriba",
                "moved_down": "Pistas seleccionadas movidas abajo",
                "deleted_tracks": "Eliminadas {count} pistas",
                "action_undone": "Última acción deshecha",
                "error_no_selection": "Error: ¡No hay pistas seleccionadas!",
                "nothing_to_undo": "Error: Nada que deshacer",
                "action_redone": "Acción rehecha",
                "edit_paths_window_title": "Editor de rutas de pistas",
                "new_path_label": "Ruta completa para pistas seleccionadas:",
                "path_example_hint": "Ejemplo: /storage/0/emulated/Music/ \n              D:/Music/Ambient/Nature/",
                "apply_button": "Aplicar",
                "cancel_button": "Cancelar",
                "error_empty_path": "Error: La ruta no puede estar vacía",
                "paths_updated": "Rutas de pistas actualizadas correctamente",
                "folder_entry_tooltip": " Haga clic con el botón derecho para borrar el campo ",
                "multiple_playlists_loaded": "Se cargaron {count} listas de reproducción",
                "tree_tooltip": " Haga clic con el botón derecho del ratón para abrir el editor de rutas "
            },
            "fr-fr": {
                "window_title_generator": "Générateur de playlists",
                "window_title_editor": "Éditeur de playlists",
                "language_name": "Français",
                "music_folder_label": "Dossier musical :",
                "browse_button": "Parcourir",
                "playlist_name_label": "Nom de la playlist :",
                "seed_label": "Graine (laisser vide pour aléatoire) :",
                "reverse_step_label": "Pas inversé (0=désactivé, 1-20) :",
                "seed_format_label": "Format de graine :",
                "shadow_seed_check": "Utiliser une graine secondaire pour un mélange complexe",
                "generate_button": "Générer la playlist",
                "language_label": "Langue :",
                "seed_formats": ["Chiffres uniquement", "Chiffres et lettres"],
                "default_playlist_name": "Ma_playlist",
                "error_open_editor": "Erreur d'ouverture de l'éditeur : {error}",
                "error_save_settings": "Erreur de sauvegarde des paramètres : {error}",
                "error_no_music_folder": "Erreur : Spécifiez un dossier musical !",
                "error_no_playlist_name": "Erreur : Spécifiez un nom de playlist !",
                "error_folder_not_exist": "Erreur : Le dossier n'existe pas !",
                "error_reverse_step": "Erreur : Le pas inversé doit être entre 0 et 20 !",
                "error_no_audio_files": "Erreur : Aucun fichier audio supporté dans le dossier !",
                "seed_info_shadow": "Graine principale : {seed} \nGraine secondaire : {shadow_seed} \nPas inversé : {step}",
                "seed_info_step": "Graine principale : {seed} | Pas inversé : {step}",
                "seed_info_basic": "Graine principale : {seed}",
                "playlist_created": "Playlist créée ! {info}",
                "error_scanning_folder": "Erreur de scan du dossier : {error}",
                "error_invalid_path": "Erreur : Caractères invalides dans le chemin",
                "track_number": "№",
                "track_name": "Nom de la piste",
                "shuffle_button": "Mélanger",
                "save_button": "Enregistrer",
                "error": "Erreur",
                "error_load_playlist": "Échec du chargement de la playlist : {error}",
                "error_no_tracks": "Aucune piste à sauvegarder",
                "error_save": "Erreur de sauvegarde",
                "seed_info_value": "Graine",
                "reverse_info_value": "Pas inversé",
                "playlist_saved": "Playlist enregistrée : {name}",
                "shuffled": "melangee",
                "moved_up": "Pistes sélectionnées déplacées vers le haut",
                "moved_down": "Pistes sélectionnées déplacées vers le bas",
                "deleted_tracks": "{count} pistes supprimées",
                "action_undone": "Dernière action annulée",
                "error_no_selection": "Erreur : Aucune piste sélectionnée !",
                "nothing_to_undo": "Erreur : Rien à annuler",
                "action_redone": "Action refaite",
                "edit_paths_window_title": "Éditeur de chemins de pistes",
                "new_path_label": "Chemin complet pour les pistes sélectionnées:",
                "path_example_hint": "Exemple: /storage/0/emulated/Music/ \n               D:/Music/Ambient/Nature/",
                "apply_button": "Appliquer",
                "cancel_button": "Annuler",
                "error_empty_path": "Erreur: Le chemin ne peut pas être vide",
                "paths_updated": "Chemins des pistes mis à jour avec succès",
                "folder_entry_tooltip": " Cliquez droit pour effacer le champ ",
                "multiple_playlists_loaded": "{count} listes de lecture chargées",
                "tree_tooltip": " Cliquez avec le bouton droit de la souris pour ouvrir l'éditeur de chemins "
            },
            "de-de": {
				"window_title_generator": "Playlist-Generator",
                "window_title_editor": "Playlist-Editor",
                "language_name": "Deutsch",
				"music_folder_label": "Musikordner:",
				"browse_button": "Durchsuchen",
				"playlist_name_label": "Playlist-Name:",
				"seed_label": "Seed (leer lassen für zufällig):",
				"reverse_step_label": "Umkehrschritt (0=aus, 1-20):",
				"seed_format_label": "Seed-Format:",
				"shadow_seed_check": "Schatten-Seed für erweitertes Mischen verwenden",
				"generate_button": "Playlist erstellen",
				"language_label": "Sprache:",
				"seed_formats": ["Nur Zahlen", "Zahlen und Buchstaben"],
				"default_playlist_name": "Meine_Playlist",
				"error_open_editor": "Fehler beim Öffnen des Editors: {error}",
				"error_save_settings": "Fehler beim Speichern der Einstellungen: {error}",
				"error_no_music_folder": "Fehler: Musikordner angeben!",
				"error_no_playlist_name": "Fehler: Playlist-Namen angeben!",
				"error_folder_not_exist": "Fehler: Ordner existiert nicht!",
				"error_reverse_step": "Fehler: Umkehrschritt muss zwischen 0 und 20 liegen!",
				"error_no_audio_files": "Fehler: Keine unterstützten Audiodateien im angegebenen Ordner!",
				"seed_info_shadow": "Haupt-Seed: {seed} \nSchatten-Seed: {shadow_seed} \nUmkehrschritt: {step}",
				"seed_info_step": "Haupt-Seed: {seed} | Umkehrschritt: {step}",
				"seed_info_basic": "Haupt-Seed: {seed}",
				"playlist_created": "Playlist erstellt! {info}",
				"error_scanning_folder": "Fehler beim Ordnerscan: {error}",
				"error_invalid_path": "Fehler: Ungültige Zeichen im Pfad",
                "track_number": "№",
                "track_name": "Titelname",
                "shuffle_button": "Mischen",
                "save_button": "Speichern",
                "error": "Fehler",
                "error_load_playlist": "Playlist konnte nicht geladen werden: {error}",
                "error_no_tracks": "Keine Titel zum Speichern",
                "error_save": "Speicherfehler",
                "editor_seed_info_step": "Gemischt! Seed: {seed} | Umkehrschritt: {step}",
                "editor_seed_info_basic": "Gemischt! Seed: {seed}",
                "seed_info_value": "Seed",
                "reverse_info_value": "Umkehrschritt",
                "playlist_saved": "Playlist gespeichert: {name}",
                "shuffled": "gemischt",
                "moved_up": "Ausgewählte Titel nach oben verschoben",
                "moved_down": "Ausgewählte Titel nach unten verschoben",
                "deleted_tracks": "{count} Titel gelöscht",
                "action_undone": "Letzte Aktion rückgängig gemacht",
                "error_no_selection": "Fehler: Keine Titel ausgewählt!",
                "nothing_to_undo": "Fehler: Nichts rückgängig zu machen",
                "action_redone": "Aktion wiederhergestellt",
                "edit_paths_window_title": "Track-Pfade-Editor",
                "new_path_label": "Vollständiger Pfad für ausgewählte Tracks:",
                "path_example_hint": "Beispiel: /storage/0/emulated/Music/ \n              D:/Music/Ambient/Nature/",
                "apply_button": "Übernehmen",
                "cancel_button": "Abbrechen",
                "error_empty_path": "Fehler: Pfad darf nicht leer sein",
                "paths_updated": "Track-Pfade erfolgreich aktualisiert",
                "folder_entry_tooltip": " Rechtsklick, um das Feld zu leeren ",
                "multiple_playlists_loaded": "{count} Wiedergabelisten geladen",
                "tree_tooltip": " Rechtsklick, um den Pfadeditor zu öffnen "
            },
            "it-it": {
                "window_title_generator": "Generatore di Playlist",
                "window_title_editor": "Editor di Playlist",
                "language_name": "Italiano",
                "music_folder_label": "Cartella musicale:",
                "browse_button": "Sfoglia",
                "playlist_name_label": "Nome playlist:",
                "seed_label": "Seed (lasciare vuoto per casuale):",
                "reverse_step_label": "Passo inverso (0=disattivato, 1-20):",
                "seed_format_label": "Formato seed:",
                "shadow_seed_check": "Usa seed ombra per mescolamento avanzato",
                "generate_button": "Crea playlist",
                "language_label": "Lingua:",
                "seed_formats": ["Solo numeri", "Numeri e lettere"],
                "default_playlist_name": "Mia_playlist",
                "error_open_editor": "Errore apertura editor: {error}",
                "error_save_settings": "Errore salvataggio impostazioni: {error}",
                "error_no_music_folder": "Errore: Specificare cartella musicale!",
                "error_no_playlist_name": "Errore: Specificare nome playlist!",
                "error_folder_not_exist": "Errore: La cartella non esiste!",
                "error_reverse_step": "Errore: Il passo inverso deve essere tra 0 e 20!",
                "error_no_audio_files": "Errore: Nessun file audio supportato nella cartella specificata!",
                "seed_info_shadow": "Seed principale: {seed} \nSeed ombra: {shadow_seed} \nPasso inverso: {step}",
                "seed_info_step": "Seed principale: {seed} | Passo inverso: {step}",
                "seed_info_basic": "Seed principale: {seed}",
                "playlist_created": "Playlist creata! {info}",
                "error_scanning_folder": "Errore scansione cartella: {error}",
                "error_invalid_path": "Errore: Caratteri non validi nel percorso",
                "track_number": "№",
                "track_name": "Nome traccia",
                "shuffle_button": "Mescola",
                "save_button": "Salva",
                "error": "Errore",
                "error_load_playlist": "Errore caricamento playlist: {error}",
                "error_no_tracks": "Nessuna traccia da salvare",
                "error_save": "Errore salvataggio",
                "editor_seed_info_step": "Mescolato! Seed: {seed} | Passo inverso: {step}",
                "editor_seed_info_basic": "Mescolato! Seed: {seed}",
                "seed_info_value": "Seed",
                "reverse_info_value": "Passo inverso",
                "playlist_saved": "Playlist salvata: {name}",
                "shuffled": "mescolato",
                "moved_up": "Tracce selezionate spostate in alto",
                "moved_down": "Tracce selezionate spostate in basso",
                "deleted_tracks": "Eliminate {count} tracce",
                "action_undone": "Ultima operazione annullata",
                "error_no_selection": "Errore: Nessuna traccia selezionata!",
                "nothing_to_undo": "Errore: Niente da annullare",
                "action_redone": "Azione ripetuta",
                "edit_paths_window_title": "Editor percorso tracce",
                "new_path_label": "Percorso completo per le tracce selezionate:",
                "path_example_hint": "Esempio: /storage/0/emulated/Music/ \n               D:/Music/Ambient/Nature/",
                "apply_button": "Applica",
                "cancel_button": "Annulla",
                "error_empty_path": "Errore: Il percorso non può essere vuoto",
                "paths_updated": "Percorsi tracce aggiornati con successo",
                "folder_entry_tooltip": " Fare clic con il tasto destro del mouse per cancellare il campo ",
                "multiple_playlists_loaded": "Caricati {count} playlist",
                "tree_tooltip": " Fare clic con il tasto destro del mouse per aprire l'editor dei percorsi "
            },
            "pl-pl": {
                "window_title_generator": "Generator playlist",
                "window_title_editor": "Edytor playlist",
                "language_name": "Polski",
                "music_folder_label": "Folder z muzyką:",
                "browse_button": "Przeglądaj",
                "playlist_name_label": "Nazwa playlisty:",
                "seed_label": "Ziarno (pozostaw puste dla losowego):",
                "reverse_step_label": "Krok odwrotny (0=wył, 1-20):",
                "seed_format_label": "Format ziarna:",
                "shadow_seed_check": "Użyj cieniowego ziarna dla zaawansowanego mieszania",
                "generate_button": "Utwórz playlistę",
                "language_label": "Język:",
                "seed_formats": ["Tylko cyfry", "Cyfry i litery"],
                "default_playlist_name": "Moja_playlista",
                "error_open_editor": "Błąd otwarcia edytora: {error}",
                "error_save_settings": "Błąd zapisu ustawień: {error}",
                "error_no_music_folder": "Błąd: Wskaż folder z muzyką!",
                "error_no_playlist_name": "Błąd: Podaj nazwę playlisty!",
                "error_folder_not_exist": "Błąd: Folder nie istnieje!",
                "error_reverse_step": "Błąd: Krok odwrotny musi być między 0 a 20!",
                "error_no_audio_files": "Błąd: Brak obsługiwanych plików audio w wybranym folderze!",
                "seed_info_shadow": "Główne ziarno: {seed} \nCieniowe ziarno: {shadow_seed} \nKrok odwrotny: {step}",
                "seed_info_step": "Główne ziarno: {seed} | Krok odwrotny: {step}",
                "seed_info_basic": "Główne ziarno: {seed}",
                "playlist_created": "Playlista utworzona! {info}",
                "error_scanning_folder": "Błąd skanowania folderu: {error}",
                "error_invalid_path": "Błąd: Niedozwolone znaki w ścieżce",
                "track_number": "№",
                "track_name": "Nazwa utworu",
                "shuffle_button": "Wymieszaj",
                "save_button": "Zapisz",
                "error": "Błąd",
                "error_load_playlist": "Błąd ładowania playlisty: {error}",
                "error_no_tracks": "Brak utworów do zapisania",
                "error_save": "Błąd zapisu",
                "editor_seed_info_step": "Wymieszano! Ziarno: {seed} | Krok odwrotny: {step}",
                "editor_seed_info_basic": "Wymieszano! Ziarno: {seed}",
                "seed_info_value": "Ziarno",
                "reverse_info_value": "Krok odwrotny",
                "playlist_saved": "Playlista zapisana: {name}",
                "shuffled": "wymieszana",
                "moved_up": "Wybrane utwory przeniesione w górę",
                "moved_down": "Wybrane utwory przeniesione w dół",
                "deleted_tracks": "Usunięto {count} utworów",
                "action_undone": "Ostatnia czynność cofnięta",
                "error_no_selection": "Błąd: Nie wybrano żadnych utworów!",
                "nothing_to_undo": "Błąd: Nic do cofnięcia",
                "action_redone": "Czynność ponowiona",
                "edit_paths_window_title": "Edytor ścieżek utworów",
                "new_path_label": "Pełna ścieżka dla wybranych utworów:",
                "path_example_hint": "Przykład: /storage/0/emulated/Music/ \n               D:/Music/Ambient/Nature/",
                "apply_button": "Zastosuj",
                "cancel_button": "Anuluj",
                "error_empty_path": "Błąd: Ścieżka nie może być pusta",
                "paths_updated": "Ścieżki utworów pomyślnie zaktualizowane",
                "folder_entry_tooltip": " Kliknij prawym przyciskiem myszy, aby wyczyścić pole ",
                "multiple_playlists_loaded": "Załadowano {count} playlist",
                "tree_tooltip": " Kliknij prawym przyciskiem myszy, aby otworzyć edytor ścieżek "
            },
            "tr-tr": {
                "window_title_generator": "Çalma Listesi Oluşturucu",
                "window_title_editor": "Çalma Listesi Düzenleyici",
                "language_name": "Türkçe",
                "music_folder_label": "Müzik klasörü:",
                "browse_button": "Gözat",
                "playlist_name_label": "Çalma listesi adı:",
                "seed_label": "Tohum (rastgele için boş bırakın):",
                "reverse_step_label": "Ters adım (0=kapalı, 1-20):",
                "seed_format_label": "Tohum formatı:",
                "shadow_seed_check": "Gelişmiş karıştırma için gölge tohum kullan",
                "generate_button": "Çalma listesi oluştur",
                "language_label": "Dil:",
                "seed_formats": ["Sadece rakamlar", "Rakamlar ve harfler"],
                "default_playlist_name": "Benim_listem",
                "error_open_editor": "Düzenleyici açılırken hata: {error}",
                "error_save_settings": "Ayarlar kaydedilirken hata: {error}",
                "error_no_music_folder": "Hata: Müzik klasörü belirtin!",
                "error_no_playlist_name": "Hata: Çalma listesi adı belirtin!",
                "error_folder_not_exist": "Hata: Klasör mevcut değil!",
                "error_reverse_step": "Hata: Ters adım 0 ile 20 arasında olmalı!",
                "error_no_audio_files": "Hata: Belirtilen klasörde desteklenen ses dosyası yok!",
                "seed_info_shadow": "Ana tohum: {seed} \nGölge tohum: {shadow_seed} \nTers adım: {step}",
                "seed_info_step": "Ana tohum: {seed} | Ters adım: {step}",
                "seed_info_basic": "Ana tohum: {seed}",
                "playlist_created": "Çalma listesi oluşturuldu! {info}",
                "error_scanning_folder": "Klasör taranırken hata: {error}",
                "error_invalid_path": "Hata: Geçersiz yol karakterleri",
                "track_number": "№",
                "track_name": "Parça adı",
                "shuffle_button": "Karıştır",
                "save_button": "Kaydet",
                "error": "Hata",
                "error_load_playlist": "Çalma listesi yüklenemedi: {error}",
                "error_no_tracks": "Kaydedilecek parça yok",
                "error_save": "Kayıt hatası",
                "editor_seed_info_step": "Karıştırıldı! Tohum: {seed} | Ters adım: {step}",
                "editor_seed_info_basic": "Karıştırıldı! Tohum: {seed}",
                "seed_info_value": "Tohum",
                "reverse_info_value": "Ters adım",
                "playlist_saved": "Çalma listesi kaydedildi: {name}",
                "shuffled": "karıştırılmış",
                "moved_up": "Seçilen parçalar yukarı taşındı",
                "moved_down": "Seçilen parçalar aşağı taşındı",
                "deleted_tracks": "{count} parça silindi",
                "action_undone": "Son işlem geri alındı",
                "error_no_selection": "Hata: Hiç parça seçilmedi!",
                "nothing_to_undo": "Hata: Geri alınacak bir şey yok",
                "action_redone": "İşlem yeniden yapıldı",
                "edit_paths_window_title": "Parça Yolu Düzenleyici",
                "new_path_label": "Seçili parçaların tam yolu:",
                "path_example_hint": "Örnek: /storage/0/emulated/Music/ \n           D:/Music/Ambient/Nature/",
                "apply_button": "Uygula",
                "cancel_button": "İptal",
                "error_empty_path": "Hata: Yol boş olamaz",
                "paths_updated": "Parça yolları başarıyla güncellendi",
                "folder_entry_tooltip": " Alanı temizlemek için sağ tıklayın ",
                "multiple_playlists_loaded": "{count} çalma listesi yüklendi",
                "tree_tooltip": " Yol düzenleyiciyi açmak için sağ tıklayın "
            },
            "be-by": {
                "window_title_generator": "Генератар плэйлістаў",
                "window_title_editor": "Рэдактар плэйлістаў",
                "language_name": "Беларуская",
                "music_folder_label": "Папка з музыкай:",
                "browse_button": "Агляд",
                "playlist_name_label": "Імя плэйліста:",
                "seed_label": "Сід (пакіньце пустым для выпадковага):",
                "reverse_step_label": "Крок рэверсу (0=выкл, 1-20):",
                "seed_format_label": "Фармат сіду:",
                "shadow_seed_check": "Выкарыстоўваць ценявы сід для складанага перамешвання",
                "generate_button": "Стварыць плэйліст",
                "language_label": "Мова:",
                "seed_formats": ["Толькі лічбы", "Лічбы і літары"],
                "default_playlist_name": "Мой_плэйліст",
                "error_open_editor": "Памылка адкрыцця рэдактара: {error}",
                "error_save_settings": "Памылка захавання налад: {error}",
                "error_no_music_folder": "Памылка: Пакажыце папку з музыкай!",
                "error_no_playlist_name": "Памылка: Пакажыце імя плэйліста!",
                "error_folder_not_exist": "Памылка: Папка не існуе!",
                "error_reverse_step": "Памылка: Крок рэверсу павінен быць ад 0 да 20!",
                "error_no_audio_files": "Памылка: У паказанай папцы няма падтрымліваемых аўдыяфайлаў!",
                "seed_info_shadow": "Асноўны сід: {seed} \nЦенявы сід: {shadow_seed} \nКрок рэверсу: {step}",
                "seed_info_step": "Асноўны сід: {seed} | Крок рэверсу: {step}",
                "seed_info_basic": "Асноўны сід: {seed}",
                "playlist_created": "Плэйліст створаны! {info}",
                "error_scanning_folder": "Памылка сканавання папкі: {error}",
                "error_invalid_path": "Памылка: Недапушчальныя сімвалы ў шляху",
                "track_number": "№",
                "track_name": "Назва трэка",
                "shuffle_button": "Перамешаць",
                "save_button": "Захаваць",
                "error": "Памылка",
                "error_load_playlist": "Не ўдалося загрузіць плэйліст: {error}",
                "error_no_tracks": "Няма трэкаў для захавання",
                "error_save": "Памылка захавання",
                "editor_seed_info_step": "Перамешана! Сід: {seed} | Крок рэверсу: {step}",
                "editor_seed_info_basic": "Перамешана! Сід: {seed}",
                "seed_info_value": "Сід",
                "reverse_info_value": "Крок рэверсу",
                "playlist_saved": "Плэйліст захаваны: {name}",
                "shuffled": "перамешаны",
                "moved_up": "Абраныя трэкі перамешчаны ўверх",
                "moved_down": "Абраныя трэкі перамешчаны ўніз",
                "deleted_tracks": "Выдалена {count} трэкаў",
                "action_undone": "Апошняе дзеянне адменена",
                "error_no_selection": "Памылка: Не абрана ніводнага трэка!",
                "nothing_to_undo": "Памылка: Няма чаго адмяняць",
                "action_redone": "Дзеянне паўторана",
                "edit_paths_window_title": "Рэдактар шляхоў да трэкаў",
                "new_path_label": "Поўны шлях для абраных трэкаў:",
                "path_example_hint": "Напрыклад: /storage/0/emulated/Music/ \n                    D:/Music/Ambient/Nature/",
                "apply_button": "Ужыць",
                "cancel_button": "Адмяніць",
                "error_empty_path": "Памылка: Шлях не можа быць пустым",
                "paths_updated": "Шляхі да трэкаў паспяхова абноўлены",
                "folder_entry_tooltip": " Націсніце правай кнопкай мышы, каб ачысціць поле ",
                "multiple_playlists_loaded": "Загружана {count} плэйлістаў",
                "tree_tooltip": " Націсніце правай кнопкай мышы, каб адкрыць рэдактар шляхоў "
            },
            "uk-ua": {
                "window_title_generator": "Генератор плейлістів",
                "window_title_editor": "Редактор плейлістів",
                "language_name": "Українська",
                "music_folder_label": "Папка з музикою:",
                "browse_button": "Огляд",
                "playlist_name_label": "Назва плейліста:",
                "seed_label": "Сід (залиште порожнім для випадкового):",
                "reverse_step_label": "Крок реверсу (0=викл, 1-20):",
                "seed_format_label": "Формат сіду:",
                "shadow_seed_check": "Використовувати тіньовий сід для складного перемішування",
                "generate_button": "Створити плейліст",
                "language_label": "Мова:",
                "seed_formats": ["Тільки цифри", "Цифри та літери"],
                "default_playlist_name": "Мій_плейліст",
                "error_open_editor": "Помилка відкриття редактора: {error}",
                "error_save_settings": "Помилка збереження налаштувань: {error}",
                "error_no_music_folder": "Помилка: Вкажіть папку з музикою!",
                "error_no_playlist_name": "Помилка: Вкажіть назву плейліста!",
                "error_folder_not_exist": "Помилка: Папка не існує!",
                "error_reverse_step": "Помилка: Крок реверсу має бути від 0 до 20!",
                "error_no_audio_files": "Помилка: У вказаній папці немає підтримуваних аудіофайлів!",
                "seed_info_shadow": "Основний сід: {seed} \nТіньовий сід: {shadow_seed} \nКрок реверсу: {step}",
                "seed_info_step": "Основний сід: {seed} | Крок реверсу: {step}",
                "seed_info_basic": "Основний сід: {seed}",
                "playlist_created": "Плейліст створено! {info}",
                "error_scanning_folder": "Помилка сканування папки: {error}",
                "error_invalid_path": "Помилка: Неприпустимі символи у шляху",
                "track_number": "№",
                "track_name": "Назва треку",
                "shuffle_button": "Перемішати",
                "save_button": "Зберегти",
                "error": "Помилка",
                "error_load_playlist": "Не вдалося завантажити плейліст: {error}",
                "error_no_tracks": "Немає треків для збереження",
                "error_save": "Помилка збереження",
                "seed_info_value": "Сід",
                "reverse_info_value": "Крок реверсу",
                "playlist_saved": "Плейліст збережено: {name}",
                "shuffled": "перемішаний",
                "moved_up": "Вибрані треки переміщені вгору",
                "moved_down": "Вибрані треки переміщені вниз",
                "deleted_tracks": "Видалено {count} треків",
                "action_undone": "Останню дію скасовано",
                "error_no_selection": "Помилка: Не вибрано жодного треку!",
                "nothing_to_undo": "Помилка: Нічого скасовувати",
                "action_redone": "Дію повернено",
                "edit_paths_window_title": "Редактор шляхів до треків",
                "new_path_label": "Повний шлях для обраних треків:",
                "path_example_hint": "Наприклад: /storage/0/emulated/Music/ \n                    D:/Music/Ambient/Nature/",
                "apply_button": "Застосувати",
                "cancel_button": "Скасувати",
                "error_empty_path": "Помилка: Шлях не може бути порожнім",
                "paths_updated": "Шляхи до треків успішно оновлені",
                "folder_entry_tooltip": " Натисніть правою кнопкою миші, щоб очистити поле ",
                "multiple_playlists_loaded": "Завантажено {count} плейлистів",
                "tree_tooltip": " Клацніть правою кнопкою миші, щоб відкрити редактор шляхів "
            },
            "kk-kz": {
                "window_title_generator": "Плейлист генераторы",
                "window_title_editor": "Плейлист редакторы",
                "language_name": "Қазақша",
                "music_folder_label": "Музыкалық бума:",
                "browse_button": "Қарап шығу",
                "playlist_name_label": "Плейлист атауы:",
                "seed_label": "Тұқым (кездейсоқ үшін бос қалдырыңыз):",
                "reverse_step_label": "Кері қадам (0=өшіру, 1-20):",
                "seed_format_label": "Тұқым форматы:",
                "shadow_seed_check": "Күрделі аралау үшін көлеңкелі тұқымды қолдану",
                "generate_button": "Плейлист құру",
                "language_label": "Тіл:",
                "seed_formats": ["Тек сандар", "Сандар мен әріптер"],
                "default_playlist_name": "Менің_плейлистім",
                "error_open_editor": "Редакторды ашу қатесі: {error}",
                "error_save_settings": "Баптауларды сақтау қатесі: {error}",
                "error_no_music_folder": "Қате: Музыкалық буманы көрсетіңіз!",
                "error_no_playlist_name": "Қате: Плейлист атауын көрсетіңіз!",
                "error_folder_not_exist": "Қате: Бума жоқ!",
                "error_reverse_step": "Қате: Кері қадам 0-ден 20-ға дейінгі сан болуы керек!",
                "error_no_audio_files": "Қате: Көрсетілген бумада қолдау көрсетілетін аудиофайлдар жоқ!",
                "seed_info_shadow": "Негізгі тұқым: {seed} \nКөлеңкелі тұқым: {shadow_seed} \nКері қадам: {step}",
                "seed_info_step": "Негізгі тұқым: {seed} | Кері қадам: {step}",
                "seed_info_basic": "Негізгі тұқым: {seed}",
                "playlist_created": "Плейлист құрылды! {info}",
                "error_scanning_folder": "Буманы сканерлеу қатесі: {error}",
                "error_invalid_path": "Қате: Жолда қол жетімсіз таңбалар",
                "track_number": "№",
                "track_name": "Трек атауы",
                "shuffle_button": "Аралау",
                "save_button": "Сақтау",
                "error": "Қате",
                "error_load_playlist": "Плейлистті жүктеу сәтсіз аяқталды: {error}",
                "error_no_tracks": "Сақтау үшін тректер жоқ",
                "error_save": "Сақтау қатесі",
                "seed_info_value": "Тұқым",
                "reverse_info_value": "Кері қадам",
                "playlist_saved": "Плейлист сақталды: {name}",
                "shuffled": "аралас",
                "moved_up": "Таңдалған тректер жоғары жылжытылды",
                "moved_down": "Таңдалған тректер төмен жылжытылды",
                "deleted_tracks": "{count} трек жойылды",
                "action_undone": "Соңғы әрекет болдырмалды",
                "error_no_selection": "Қате: Еш трек таңдалмаған!",
                "nothing_to_undo": "Қате: Болдыратын ештеңе жоқ",
                "action_redone": "Әрекет қайталанды",
                "edit_paths_window_title": "Трек жолдары редакторы",
                "new_path_label": "Таңдалған тректердің толық жолы:",
                "path_example_hint": "Мысалы: /storage/0/emulated/Music/ \n               D:/Music/Ambient/Nature/",
                "apply_button": "Қолдану",
                "cancel_button": "Бас тарту",
                "error_empty_path": "Қате: Жол бос болмауы керек",
                "paths_updated": "Трек жолдары сәтті жаңартылды",
                "folder_entry_tooltip": " Өрісті тазалау үшін тінтуірдің оң жақ батырмасын басыңыз ",
                "multiple_playlists_loaded": "{count} плейлист жүктелді",
                "tree_tooltip": " Жол жолымен басыңыз, жолдар редакторын ашу үшін "
            },
            "sr-rs": {
                "window_title_generator": "Генератор плејлиста",
                "window_title_editor": "Уређивач плејлиста",
                "language_name": "Српски",
                "music_folder_label": "Музичка фасцикла:",
                "browse_button": "Преглед",
                "playlist_name_label": "Назив плејлисте:",
                "seed_label": "Сид (оставите празно за насумично):",
                "reverse_step_label": "Корак уназад (0=искљ, 1-20):",
                "seed_format_label": "Формат сида:",
                "shadow_seed_check": "Користи сенку сида за напредно мешање",
                "generate_button": "Направи плејлисту",
                "language_label": "Језик:",
                "seed_formats": ["Само бројеви", "Бројеви и слова"],
                "default_playlist_name": "Моја_плејлиста",
                "error_open_editor": "Грешка при отварању уређивача: {error}",
                "error_save_settings": "Грешка при чувању поставки: {error}",
                "error_no_music_folder": "Грешка: Одредите музичку фасциклу!",
                "error_no_playlist_name": "Грешка: Одредите назив плејлисте!",
                "error_folder_not_exist": "Грешка: Фасцикла не постоји!",
                "error_reverse_step": "Грешка: Корак уназад мора бити број од 0 до 20!",
                "error_no_audio_files": "Грешка: Нема подржаних аудио фајлова у фасцикли!",
                "seed_info_shadow": "Главни сид: {seed} \nСенка сида: {shadow_seed} \nКорак уназад: {step}",
                "seed_info_step": "Главни сид: {seed} | Корак уназад: {step}",
                "seed_info_basic": "Главни сид: {seed}",
                "playlist_created": "Плејлиста направљена! {info}",
                "error_scanning_folder": "Грешка при скенирању фасцикле: {error}",
                "error_invalid_path": "Грешка: Неисправни знакови у путањи",
                "track_number": "№",
                "track_name": "Назив нумере",
                "shuffle_button": "Измешај",
                "save_button": "Сачувај",
                "error": "Грешка",
                "error_load_playlist": "Грешка при учитавању плејлисте: {error}",
                "error_no_tracks": "Нема нумера за чување",
                "error_save": "Грешка при чувању",
                "seed_info_value": "Сид",
                "reverse_info_value": "Корак уназад",
                "playlist_saved": "Плејлиста сачувана: {name}",
                "shuffled": "измешана",
                "moved_up": "Изабране песме померене нагоре",
                "moved_down": "Изабране песме померене надоле",
                "deleted_tracks": "Обрисано {count} песама",
                "action_undone": "Последња радња опозвана",
                "error_no_selection": "Грешка: Није изабрана ниједна песма!",
                "nothing_to_undo": "Грешка: Нема шта да се опозове",
                "action_redone": "Радња поновљена",
                "edit_paths_window_title": "Уређивач путања до нумера",
                "new_path_label": "Пуна путања за изабране нумере:",
                "path_example_hint": "Пример: /storage/0/emulated/Music/ \n               D:/Music/Ambient/Nature/",
                "apply_button": "Примени",
                "cancel_button": "Откажи",
                "error_empty_path": "Грешка: Путања не може бити празна",
                "paths_updated": "Путање до нумера успешно ажуриране",
                "folder_entry_tooltip": " Кликните десним тастером да бисте очистили поље ",
                "multiple_playlists_loaded": "Учитано {count} плејлиста",
                "tree_tooltip": " Кликните десним тастером миша да бисте отворили уређивач путања "
            },
            "nl-nl": {
                "window_title_generator": "Afspeellijst Generator",
                "window_title_editor": "Afspeellijst Editor",
                "language_name": "Nederlands",
                "music_folder_label": "Muziekmap:",
                "browse_button": "Bladeren",
                "playlist_name_label": "Afspeellijstnaam:",
                "seed_label": "Seed (leeg laten voor willekeurig):",
                "reverse_step_label": "Omgekeerde stap (0=uit, 1-20):",
                "seed_format_label": "Seed-formaat:",
                "shadow_seed_check": "Schaduw-seed gebruiken voor geavanceerd shufflen",
                "generate_button": "Afspeellijst genereren",
                "language_label": "Taal:",
                "seed_formats": ["Alleen cijfers", "Cijfers en letters"],
                "default_playlist_name": "Mijn_afspeellijst",
                "error_open_editor": "Fout bij openen editor: {error}",
                "error_save_settings": "Fout bij opslaan instellingen: {error}",
                "error_no_music_folder": "Fout: Geef een muziekmap op!",
                "error_no_playlist_name": "Fout: Geef een afspeellijstnaam op!",
                "error_folder_not_exist": "Fout: Map bestaat niet!",
                "error_reverse_step": "Fout: Omgekeerde stap moet tussen 0 en 20 liggen!",
                "error_no_audio_files": "Fout: Geen ondersteunde audiobestanden in map!",
                "seed_info_shadow": "Hoofd-seed: {seed} \nSchaduw-seed: {shadow_seed} \nOmgekeerde stap: {step}",
                "seed_info_step": "Hoofd-seed: {seed} | Omgekeerde stap: {step}",
                "seed_info_basic": "Hoofd-seed: {seed}",
                "playlist_created": "Afspeellijst aangemaakt! {info}",
                "error_scanning_folder": "Fout bij scannen map: {error}",
                "error_invalid_path": "Fout: Ongeldige tekens in pad",
                "track_number": "№",
                "track_name": "Nummernaam",
                "shuffle_button": "Shufflen",
                "save_button": "Opslaan",
                "error": "Fout",
                "error_load_playlist": "Fout bij laden afspeellijst: {error}",
                "error_no_tracks": "Geen nummers om op te slaan",
                "error_save": "Opslagfout",
                "editor_seed_info_step": "Geshuffled! Seed: {seed} | Omgekeerde stap: {step}",
                "editor_seed_info_basic": "Geshuffled! Seed: {seed}",
                "seed_info_value": "Seed",
                "reverse_info_value": "Omgekeerde stap",
                "playlist_saved": "Afspeellijst opgeslagen: {name}",
                "shuffled": "geshuffled",
                "moved_up": "Geselecteerde nummers naar boven verplaatst",
                "moved_down": "Geselecteerde nummers naar beneden verplaatst",
                "deleted_tracks": "{count} nummers verwijderd",
                "action_undone": "Laatste actie ongedaan gemaakt",
                "error_no_selection": "Fout: Geen nummers geselecteerd!",
                "nothing_to_undo": "Fout: Niets om ongedaan te maken",
                "action_redone": "Actie opnieuw uitgevoerd",
                "edit_paths_window_title": "Trackpaden Bewerker",
                "new_path_label": "Volledig pad voor geselecteerde tracks:",
                "path_example_hint": "Voorbeeld: /storage/0/emulated/Music/ \n                  D:/Music/Ambient/Nature/",
                "apply_button": "Toepassen",
                "cancel_button": "Annuleren",
                "error_empty_path": "Fout: Pad mag niet leeg zijn",
                "paths_updated": "Trackpaden succesvol bijgewerkt",
                "folder_entry_tooltip": " Rechtsklik om het veld te wissen ",
                "multiple_playlists_loaded": "{count} afspeellijsten geladen",
                "tree_tooltip": " Klik met de rechtermuisknop om de pad-editor te openen "
            },
            "es-mx": {
                "window_title_generator": "Generador de listas de reproducción",
                "window_title_editor": "Editor de listas de reproducción",
                "language_name": "Español Mexicano",
                "music_folder_label": "Carpeta de música:",
                "browse_button": "Explorar",
                "playlist_name_label": "Nombre de la lista:",
                "seed_label": "Semilla (dejar vacío para aleatorio):",
                "reverse_step_label": "Paso inverso (0=desactivado, 1-20):",
                "seed_format_label": "Formato de semilla:",
                "shadow_seed_check": "Usar semilla oculta para mezcla avanzada",
                "generate_button": "Crear lista",
                "language_label": "Idioma:",
                "seed_formats": ["Sólo números", "Números y letras"],
                "default_playlist_name": "Mi_lista",
                "error_open_editor": "Error al abrir editor: {error}",
                "error_save_settings": "Error al guardar configuraciones: {error}",
                "error_no_music_folder": "¡Error: Especifica carpeta de música!",
                "error_no_playlist_name": "¡Error: Especifica nombre de lista!",
                "error_folder_not_exist": "¡Error: ¡La carpeta no existe!",
                "error_reverse_step": "¡Error: El paso inverso debe ser entre 0 y 20!",
                "error_no_audio_files": "¡Error: No hay archivos de audio en la carpeta!",
                "seed_info_shadow": "Semilla principal: {seed} \nSemilla oculta: {shadow_seed} \nPaso inverso: {step}",
                "seed_info_step": "Semilla principal: {seed} | Paso inverso: {step}",
                "seed_info_basic": "Semilla principal: {seed}",
                "playlist_created": "¡Lista creada! {info}",
                "error_scanning_folder": "Error al escanear carpeta: {error}",
                "error_invalid_path": "Error: Caracteres inválidos en ruta",
                "track_number": "№",
                "track_name": "Nombre de canción",
                "shuffle_button": "Mezclar",
                "save_button": "Guardar",
                "error": "Error",
                "error_load_playlist": "Error al cargar lista: {error}",
                "error_no_tracks": "No hay canciones para guardar",
                "error_save": "Error al guardar",
                "editor_seed_info_step": "¡Mezclado! Semilla: {seed} | Paso inverso: {step}",
                "editor_seed_info_basic": "¡Mezclado! Semilla: {seed}",
                "seed_info_value": "Semilla",
                "reverse_info_value": "Paso inverso",
                "playlist_saved": "Lista guardada: {name}",
                "shuffled": "mezclada",
                "moved_up": "Canciones seleccionadas movidas arriba",
                "moved_down": "Canciones seleccionadas movidas abajo",
                "deleted_tracks": "{count} canciones eliminadas",
                "action_undone": "Última acción deshecha",
                "error_no_selection": "Error: ¡No hay canciones seleccionadas!",
                "nothing_to_undo": "Error: Nada que deshacer",
                "action_redone": "Acción rehecha",
                "edit_paths_window_title": "Editor de rutas de pistas",
                "new_path_label": "Ruta completa para pistas seleccionadas:",
                "path_example_hint": "Ejemplo: /storage/0/emulated/Music/ \n              D:/Music/Ambient/Nature/",
                "apply_button": "Aplicar",
                "cancel_button": "Cancelar",
                "error_empty_path": "Error: La ruta no puede estar vacía",
                "paths_updated": "Rutas de pistas actualizadas correctamente",
                "folder_entry_tooltip": " Haga clic derecho para borrar el campo ",
                "multiple_playlists_loaded": "Se cargaron {count} listas de reproducción",
                "tree_tooltip": " Haz clic derecho para abrir el editor de rutas "
            },
            "pt-pt": {
                "window_title_generator": "Gerador de Playlists",
                "window_title_editor": "Editor de Playlists",
                "language_name": "Português",
                "music_folder_label": "Pasta de músicas:",
                "browse_button": "Procurar",
                "playlist_name_label": "Nome da playlist:",
                "seed_label": "Seed (deixe vazio para aleatório):",
                "reverse_step_label": "Passo reverso (0=desligado, 1-20):",
                "seed_format_label": "Formato do seed:",
                "shadow_seed_check": "Usar seed secundário para mistura avançada",
                "generate_button": "Criar playlist",
                "language_label": "Idioma:",
                "seed_formats": ["Apenas dígitos", "Dígitos e letras"],
                "default_playlist_name": "Minha_playlist",
                "error_open_editor": "Erro ao abrir editor: {error}",
                "error_save_settings": "Erro ao salvar configurações: {error}",
                "error_no_music_folder": "Erro: Especifique a pasta de músicas!",
                "error_no_playlist_name": "Erro: Especifique o nome da playlist!",
                "error_folder_not_exist": "Erro: A pasta não existe!",
                "error_reverse_step": "Erro: O passo reverso deve ser entre 0 e 20!",
                "error_no_audio_files": "Erro: Nenhum arquivo de áudio suportado na pasta especificada!",
                "seed_info_shadow": "Seed principal: {seed} \nSeed secundário: {shadow_seed} \nPasso reverso: {step}",
                "seed_info_step": "Seed principal: {seed} | Passo reverso: {step}",
                "seed_info_basic": "Seed principal: {seed}",
                "playlist_created": "Playlist criada! {info}",
                "error_scanning_folder": "Erro ao escanear pasta: {error}",
                "error_invalid_path": "Erro: Caracteres inválidos no caminho",
                "track_number": "№",
                "track_name": "Nome da faixa",
                "shuffle_button": "Misturar",
                "save_button": "Salvar",
                "error": "Erro",
                "error_load_playlist": "Falha ao carregar playlist: {error}",
                "error_no_tracks": "Nenhuma faixa para salvar",
                "error_save": "Erro ao salvar",
                "seed_info_value": "Seed",
                "reverse_info_value": "Passo reverso",
                "playlist_saved": "Playlist salva: {name}",
                "shuffled": "misturada",
                "moved_up": "Faixas selecionadas movidas para cima",
                "moved_down": "Faixas selecionadas movidas para baixo",
                "deleted_tracks": "{count} faixas eliminadas",
                "action_undone": "Última ação desfeita",
                "error_no_selection": "Erro: Nenhuma faixa selecionada!",
                "nothing_to_undo": "Erro: Nada para desfazer",
                "action_redone": "Ação refeita",
                "edit_paths_window_title": "Editor de caminhos de faixas",
                "new_path_label": "Caminho completo para faixas selecionadas:",
                "path_example_hint": "Exemplo: /storage/0/emulated/Music/ \n               D:/Music/Ambient/Nature/",
                "apply_button": "Aplicar",
                "cancel_button": "Cancelar",
                "error_empty_path": "Erro: O caminho não pode estar vazio",
                "paths_updated": "Caminhos de faixas atualizados com sucesso",
                "folder_entry_tooltip": " Clique com o botão direito para limpar o campo ",
                "multiple_playlists_loaded": "Carregadas {count} listas de reprodução",
                "tree_tooltip": " Clique com o botão direito do rato para abrir o editor de caminhos "
            },
            "pt-br": {
                "window_title_generator": "Gerador de Playlists",
                "window_title_editor": "Editor de Playlists",
                "language_name": "Português Brasileiro",
                "music_folder_label": "Pasta de músicas:",
                "browse_button": "Procurar",
                "playlist_name_label": "Nome da playlist:",
                "seed_label": "Seed (deixe vazio para aleatório):",
                "reverse_step_label": "Passo reverso (0=desligado, 1-20):",
                "seed_format_label": "Formato do seed:",
                "shadow_seed_check": "Usar seed oculto para mistura avançada",
                "generate_button": "Criar playlist",
                "language_label": "Idioma:",
                "seed_formats": ["Apenas números", "Números e letras"],
                "default_playlist_name": "Minha_playlist",
                "error_open_editor": "Erro ao abrir editor: {error}",
                "error_save_settings": "Erro ao salvar configurações: {error}",
                "error_no_music_folder": "Erro: Especifique a pasta de músicas!",
                "error_no_playlist_name": "Erro: Especifique o nome da playlist!",
                "error_folder_not_exist": "Erro: A pasta não existe!",
                "error_reverse_step": "Erro: O passo reverso deve ser entre 0 e 20!",
                "error_no_audio_files": "Erro: Nenhum arquivo de áudio na pasta!",
                "seed_info_shadow": "Seed principal: {seed} \nSeed oculto: {shadow_seed} \nPasso reverso: {step}",
                "seed_info_step": "Seed principal: {seed} | Passo reverso: {step}",
                "seed_info_basic": "Seed principal: {seed}",
                "playlist_created": "Playlist criada! {info}",
                "error_scanning_folder": "Erro ao escanear pasta: {error}",
                "error_invalid_path": "Erro: Caracteres inválidos no caminho",
                "track_number": "№",
                "track_name": "Nome da faixa",
                "shuffle_button": "Embaralhar",
                "save_button": "Salvar",
                "error": "Erro",
                "error_load_playlist": "Erro ao carregar playlist: {error}",
                "error_no_tracks": "Nenhuma faixa para salvar",
                "error_save": "Erro ao salvar",
                "editor_seed_info_step": "Embaralhado! Seed: {seed} | Passo reverso: {step}",
                "editor_seed_info_basic": "Embaralhado! Seed: {seed}",
                "seed_info_value": "Seed",
                "reverse_info_value": "Passo reverso",
                "playlist_saved": "Playlist salva: {name}",
                "shuffled": "embaralhada",
                "moved_up": "Músicas selecionadas movidas para cima",
                "moved_down": "Músicas selecionadas movidas para baixo",
                "deleted_tracks": "{count} músicas excluídas",
                "action_undone": "Última ação desfeita",
                "error_no_selection": "Erro: Nenhuma música selecionada!",
                "nothing_to_undo": "Erro: Nada para desfazer",
                "action_redone": "Ação refeita",
                "edit_paths_window_title": "Editor de caminhos de faixas",
                "new_path_label": "Caminho completo para faixas selecionadas:",
                "path_example_hint": "Exemplo: /storage/0/emulated/Music/ \n               D:/Music/Ambient/Nature/",
                "apply_button": "Aplicar",
                "cancel_button": "Cancelar",
                "error_empty_path": "Erro: O caminho não pode estar vazio",
                "paths_updated": "Caminhos de faixas atualizados com sucesso",
                "folder_entry_tooltip": " Clique com o botão direito para limpar o campo ",
                "multiple_playlists_loaded": "{count} playlists carregadas",
                "tree_tooltip": " Clique com o botão direito do mouse para abrir o editor de caminhos "
            },
            "zh-cn": {
                "window_title_generator": "播放列表生成器",
                "window_title_editor": "播放列表编辑器",
                "language_name": "简体中文",
                "music_folder_label": "音乐文件夹:",
                "browse_button": "浏览",
                "playlist_name_label": "播放列表名称:",
                "seed_label": "种子 (留空为随机):",
                "reverse_step_label": "反转步长 (0=关闭, 1-20):",
                "seed_format_label": "种子格式:",
                "shadow_seed_check": "使用隐藏种子进行高级混排",
                "generate_button": "生成播放列表",
                "language_label": "语言:",
                "seed_formats": ["仅数字", "数字和字母"],
                "default_playlist_name": "我的播放列表",
                "error_open_editor": "打开编辑器错误: {error}",
                "error_save_settings": "保存设置错误: {error}",
                "error_no_music_folder": "错误: 请指定音乐文件夹!",
                "error_no_playlist_name": "错误: 请指定播放列表名称!",
                "error_folder_not_exist": "错误: 文件夹不存在!",
                "error_reverse_step": "错误: 反转步长必须为0到20之间的数字!",
                "error_no_audio_files": "错误: 指定文件夹中没有支持的音频文件!",
                "seed_info_shadow": "主种子: {seed} \n隐藏种子: {shadow_seed} \n反转步长: {step}",
                "seed_info_step": "主种子: {seed} | 反转步长: {step}",
                "seed_info_basic": "主种子: {seed}",
                "playlist_created": "播放列表已创建! {info}",
                "error_scanning_folder": "扫描文件夹错误: {error}",
                "error_invalid_path": "错误: 路径中的字符无效",
                "track_number": "序号",
                "track_name": "曲目名称",
                "shuffle_button": "随机排序",
                "save_button": "保存",
                "error": "错误",
                "error_load_playlist": "加载播放列表失败: {error}",
                "error_no_tracks": "没有可保存的曲目",
                "error_save": "保存错误",
                "editor_seed_info_step": "已随机排序! 种子: {seed} | 反转步长: {step}",
                "editor_seed_info_basic": "已随机排序! 种子: {seed}",
                "seed_info_value": "种子",
                "reverse_info_value": "反转步长",
                "playlist_saved": "播放列表已保存: {name}",
                "shuffled": "已混排",
                "moved_up": "已上移选定曲目",
                "moved_down": "已下移选定曲目",
                "deleted_tracks": "已删除{count}首曲目",
                "action_undone": "已撤销上一操作",
                "error_no_selection": "错误：未选择任何曲目！",
                "nothing_to_undo": "错误：无操作可撤销",
                "action_redone": "操作已重做",
                "edit_paths_window_title": "音轨路径编辑器",
                "new_path_label": "所选音轨的完整路径：",
                "path_example_hint": "例如：/storage/0/emulated/Music/ \n            D:/Music/Ambient/Nature/",
                "apply_button": "应用",
                "cancel_button": "取消",
                "error_empty_path": "错误：路径不能为空",
                "paths_updated": "音轨路径更新成功",
                "folder_entry_tooltip": " 右键点击清除字段 ",
                "multiple_playlists_loaded": "已加载{count}个播放列表",
                "tree_tooltip": " 右键单击以打开路径编辑器 "
            },
            "ko-kr": {
                "window_title_generator": "플레이리스트 생성기",
                "window_title_editor": "플레이리스트 편집기",
                "language_name": "한국어",
                "music_folder_label": "음악 폴더:",
                "browse_button": "찾아보기",
                "playlist_name_label": "플레이리스트 이름:",
                "seed_label": "시드 (비워두면 랜덤):",
                "reverse_step_label": "역방향 단계 (0=끔, 1-20):",
                "seed_format_label": "시드 형식:",
                "shadow_seed_check": "고급 셔플링을 위해 숨겨진 시드 사용",
                "generate_button": "플레이리스트 생성",
                "language_label": "언어:",
                "seed_formats": ["숫자만", "숫자와 문자"],
                "default_playlist_name": "내_플레이리스트",
                "error_open_editor": "편집기 열기 오류: {error}",
                "error_save_settings": "설정 저장 오류: {error}",
                "error_no_music_folder": "오류: 음악 폴더를 지정하세요!",
                "error_no_playlist_name": "오류: 플레이리스트 이름을 지정하세요!",
                "error_folder_not_exist": "오류: 폴더가 존재하지 않습니다!",
                "error_reverse_step": "오류: 역방향 단계는 0에서 20 사이여야 합니다!",
                "error_no_audio_files": "오류: 지정된 폴더에 지원되는 오디오 파일이 없습니다!",
                "seed_info_shadow": "메인 시드: {seed} \n숨겨진 시드: {shadow_seed} \n역방향 단계: {step}",
                "seed_info_step": "메인 시드: {seed} | 역방향 단계: {step}",
                "seed_info_basic": "메인 시드: {seed}",
                "playlist_created": "플레이리스트 생성 완료! {info}",
                "error_scanning_folder": "폴더 스캔 오류: {error}",
                "error_invalid_path": "오류: 경로에 잘못된 문자가 있습니다",
                "track_number": "번호",
                "track_name": "트랙 이름",
                "shuffle_button": "셔플",
                "save_button": "저장",
                "error": "오류",
                "error_load_playlist": "플레이리스트 불러오기 실패: {error}",
                "error_no_tracks": "저장할 트랙이 없습니다",
                "error_save": "저장 오류",
                "editor_seed_info_step": "셔플 완료! 시드: {seed} | 역방향 단계: {step}",
                "editor_seed_info_basic": "셔플 완료! 시드: {seed}",
                "seed_info_value": "시드",
                "reverse_info_value": "역방향 단계",
                "playlist_saved": "플레이리스트 저장됨: {name}",
                "shuffled": "셔플됨",
                "moved_up": "선택한 트랙을 위로 이동했습니다",
                "moved_down": "선택한 트랙을 아래로 이동했습니다",
                "deleted_tracks": "트랙 {count}개 삭제됨",
                "action_undone": "마지막 작업 취소됨",
                "error_no_selection": "오류: 선택된 트랙이 없습니다!",
                "nothing_to_undo": "오류: 취소할 작업이 없습니다",
                "action_redone": "작업 다시 실행됨",
                "edit_paths_window_title": "트랙 경로 편집기",
                "new_path_label": "선택한 트랙의 전체 경로:",
                "path_example_hint": "예: /storage/0/emulated/Music/ \n     D:/Music/Ambient/Nature/",
                "apply_button": "적용",
                "cancel_button": "취소",
                "error_empty_path": "오류: 경로가 비어 있을 수 없습니다",
                "paths_updated": "트랙 경로가 성공적으로 업데이트됨",
                "folder_entry_tooltip": " 필드를 지우려면 마우스 오른쪽 버튼을 클릭하세요 ",
                "multiple_playlists_loaded": "재생 목록 {count}개가 로드됨",
                "tree_tooltip": " 경로 편집기를 열려면 마우스 오른쪽 버튼을 클릭하세요 "
            }
        }
        self.lang_names = {code: data["language_name"] for code, data in self.languages.items()}
    
    
    def is_language_supported(self, lang_code):
        return lang_code in self.languages
    
    def set_language(self, lang_code):
        """Устанавливает текущий язык"""
        self.current_lang = lang_code if self.is_language_supported(lang_code) else 'en-us'
    
    def tr(self, key):
        """Возвращает переведённый текст по ключу"""
        return self.languages.get(self.current_lang, {}).get(key, key)
    
    def get_seed_format_options(self):
        """Возвращает варианты формата сида для текущего языка"""
        return self.languages.get(self.current_lang, {}).get("seed_formats", ["Digits only", "Digits and letters"])
    
    def detect_system_language(self):
        """Определяет язык системы с проверкой поддержки"""
        try:
            import locale
            sys_lang = locale.getdefaultlocale()[0].lower()
            
            # Варианты для русского
            if sys_lang in ['ru', 'ru_ru', 'ru-ru', 'russian']:
                return 'ru-ru'
            # Варианты для украинского
            elif sys_lang in ['uk', 'uk_ua', 'uk-ua', 'ukrainian']:
                return 'uk-ua'
            # Варианты для белорусского
            elif sys_lang in ['be', 'be_by', 'be-by', 'belarusian']:
                return 'be-by'
            # Варианты для казахского
            elif sys_lang in ['kk', 'kk_kz', 'kk-kz', 'kazakh']:
                return 'kk-kz'
           # Варианты для итальянского
            elif sys_lang in ['it', 'it_it', 'it-it', 'italian']:
                return 'it-it'
            # Варианты для испанского
            elif sys_lang in ['es', 'es_es', 'es-es', 'spanish', 'es_mx', 'es_ar', 'es_cl', 'es_co']:
                return 'es-es'
            # Варианты для португальского
            elif sys_lang in ['pt', 'pt_pt', 'pt-pt', 'portuguese']:
                return 'pt-pt'
            # Варианты для английского
            elif sys_lang in ['en', 'en_us', 'en-us', 'english']:
                return 'en-us'
            # Варианты для немецкого
            elif sys_lang in ['de', 'de_de', 'de-de', 'german', 'de_at', 'de_ch', 'de_li', 'de_lu']:
                return 'de-de'
            # Варианты для польского
            elif sys_lang in ['pl', 'pl_pl', 'pl-pl', 'polish']:
                return 'pl-pl'
            # Варианты для турецкого
            elif sys_lang in ['tr', 'tr_tr', 'tr-tr', 'turkish']:
                return 'tr-tr'
            # Варианты для сербского
            elif sys_lang in ['sr', 'sr_rs', 'sr-rs', 'sr_latn_rs', 'serbian']:
                return 'sr-rs'
            # Варианты для нидерландского
            elif sys_lang in ['nl', 'nl_nl', 'nl-nl', 'dutch']:
                return 'nl-nl'
            # Варианты для французкого
            elif sys_lang in ['fr', 'fr_fr', 'fr-fr', 'fr_be', 'fr_ch', 'fr_ca', 'french']:
                return 'fr-fr'
            # Варианты для мексиканского испанского
            elif sys_lang in ['es_mx', 'es-mx', 'es_mex', 'es-mex']:
                return 'es-mx'
            # Варианты для бразильского португальского
            elif sys_lang in ['pt_br', 'pt-br', 'ptb', 'portuguese_brazil']:
                return 'pt-br'
            # Варианты для китайского
            elif sys_lang in ['zh', 'zh_cn', 'zh-cn', 'chinese', 'zh_hans', 'zh-hans']:
                return 'zh-cn'
            # Варианты для корейского
            elif sys_lang in ['ko', 'ko_kr', 'ko-kr', 'korean']:
                return 'ko-kr'    
                
            # Для других языков возвращаем английский как fallback
            return 'en-us'
            
        except Exception:
            return 'en-us'  # Fallback при ошибках